services:
  laravel-docker:
    container_name: laravel-docker
    build: ./league-of-tasks-api
    ports:
      - 8000:80

  react-docker:
    container_name: react-docker
    build: ./league-of-tasks-client
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: league-of-tasks
    ports:
      - 3306:3306