<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tasks')->insert([
            [
                'task_name' => 'Faire 20 pompes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Faire 40 pompes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Faire 60 pompes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'hard',
                'reward_xp' => 30,
                'reward_gold' => 55,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Courir 5 minutes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Courir 10 minutes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Courir 20 minutes',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'hard',
                'reward_xp' => 30,
                'reward_gold' => 55,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Faire 5 minutes de yoga',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Faire 5 minutes d’étirements',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Lire 20 pages d’un livre',
                'mobility_req' => false,
                'vision_req' => true,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Lire 40 pages d’un livre',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 10 ,
                'reward_gold' => 4,
                'interest_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Lire 60 pages d’un livre',
                'mobility_req' => false,
                'vision_req' => true,
                'difficulty' => 'hard',
                'reward_xp' => 30,
                'reward_gold' => 55,
                'interest_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Noter 3 choses positives de la journée',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Boire 1.5 litres d’eau',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Planifier la journée de demain',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Apprendre 5 nouveaux mots en langue étrangère',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Écouter un podcast dans une autre langue',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'easy',
                'reward_xp' => 10,
                'reward_gold' => 15,
                'interest_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Ranger son espace de travail',
                'mobility_req' => false,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_name' => 'Passer l’aspirateur dans une pièce',
                'mobility_req' => true,
                'vision_req' => false,
                'difficulty' => 'medium',
                'reward_xp' => 20,
                'reward_gold' => 35,
                'interest_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
