name: league-of-tasks

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: league-of-tasks-tests
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: install jest v1
      run: npm install -g jest
    - name: Run tests
      run: npm run test
  
build-and-push-image-api-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ylustran
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./league-of-tasks-api
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/yllustran/league-of-tasks-api:latest
            ghcr.io/yllustran/league-of-tasks-api:${{ github.sha }}

build-and-push-image-spa-prod:
  needs:
    - tests
  permissions: write-all
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: yllustran
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./league-of-tasks-client
        build-args: |
          "MODE=prod"
        push: true
        tags: |
         ghcr.io/yllustran/league-of-tasks-client:latest
         ghcr.io/yllustran/league-of-tasks-client:${{ github.sha }}